 use_frameworks! 
platform :ios, '11.0'
target "Pod" do
pod 'Firebase'
end
pod 'GoogleSignIn'

pod 'FBSDKLoginKit'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKPlacesKit'
pod 'FBSDKMessengerShareKit'
pod 'Firebase/Core'
pod 'Firebase/Auth'


